"""initial schema

Revision ID: a7475749c243
Revises: 
Create Date: 2026-07-29 22:21:14.667681

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

from app.models.base import JSONType

# revision identifiers, used by Alembic.
revision: str = 'a7475749c243'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('working_hours', JSONType, nullable=False),
    sa.Column('holidays', JSONType, nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_calendars')),
    sa.UniqueConstraint('name', name=op.f('uq_calendars_name'))
    )
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_groups_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_template_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('api_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_api_credentials_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_credentials')),
    sa.UniqueConstraint('name', name=op.f('uq_api_credentials_name'))
    )
    op.create_table('gantt_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('template_version', sa.Integer(), nullable=False),
    sa.Column('template_snapshot', JSONType, nullable=False),
    sa.Column('params', JSONType, nullable=False),
    sa.Column('role_assignments', JSONType, nullable=False),
    sa.Column('skipped_tasks', JSONType, nullable=False),
    sa.Column('target_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('buffer_seconds', sa.Integer(), nullable=False),
    sa.Column('target_date_history', JSONType, nullable=False),
    sa.Column('baseline_resets', JSONType, nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('forecast_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health', sa.String(length=16), nullable=True),
    sa.Column('buffer_consumed_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('progress_ratio', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_gantt_cases_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gantt_cases')),
    sa.UniqueConstraint('idempotency_key', name=op.f('uq_gantt_cases_idempotency_key'))
    )
    op.create_index('idx_cases_health', 'gantt_cases', ['health'], unique=False, postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.create_index('idx_cases_status_target', 'gantt_cases', ['status', 'target_date'], unique=False)
    op.create_table('gantt_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('definition', JSONType, nullable=False),
    sa.Column('change_note', sa.Text(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_gantt_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_gantt_templates')),
    sa.UniqueConstraint('name', 'version', name='uq_template_version')
    )
    op.create_index('uq_gantt_template_draft', 'gantt_templates', ['name'], unique=True, postgresql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
    op.create_table('group_members',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_lead', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_group_members_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_group_members_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id', name=op.f('pk_group_members'))
    )
    op.create_table('notification_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('channels', JSONType, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notification_preferences_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'type', name=op.f('pk_notification_preferences'))
    )
    op.create_table('task_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('duration_default', sa.String(length=32), nullable=False),
    sa.Column('schedule_mode', sa.String(length=16), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('para_schema', JSONType, nullable=False),
    sa.Column('task_api', sa.String(length=128), nullable=True),
    sa.Column('api_mode', sa.String(length=32), nullable=True),
    sa.Column('api_config', JSONType, nullable=False),
    sa.Column('api_timeout_s', sa.Integer(), nullable=False),
    sa.Column('api_retry_max', sa.Integer(), nullable=False),
    sa.Column('api_retry_interval_s', sa.Integer(), nullable=False),
    sa.Column('api_poll_interval_s', sa.Integer(), nullable=False),
    sa.Column('allow_manual_override', sa.Boolean(), nullable=False),
    sa.Column('on_failure', sa.String(length=16), nullable=False),
    sa.Column('warn_before_s', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_task_templates_calendar_id_calendars'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_task_templates_created_by_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_templates')),
    sa.UniqueConstraint('name', name=op.f('uq_task_templates_name'))
    )
    op.create_table('case_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('source_task_template', sa.String(length=64), nullable=True),
    sa.Column('phase', sa.String(length=128), nullable=False),
    sa.Column('for_each_group', sa.String(length=128), nullable=True),
    sa.Column('for_each_index', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('schedule_mode', sa.String(length=16), nullable=False),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.Column('baseline_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('baseline_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('forecast_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('completion_source', sa.String(length=16), nullable=True),
    sa.Column('completed_by_id', sa.Integer(), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('owner_source', sa.String(length=128), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('params', JSONType, nullable=False),
    sa.Column('task_api', sa.String(length=128), nullable=True),
    sa.Column('api_mode', sa.String(length=32), nullable=True),
    sa.Column('api_config', JSONType, nullable=False),
    sa.Column('allow_manual_override', sa.Boolean(), nullable=False),
    sa.Column('on_failure', sa.String(length=16), nullable=False),
    sa.Column('is_optional', sa.Boolean(), nullable=False),
    sa.Column('warn_before_seconds', sa.Integer(), nullable=False),
    sa.Column('is_on_critical_path', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendars.id'], name=op.f('fk_case_tasks_calendar_id_calendars'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['gantt_cases.id'], name=op.f('fk_case_tasks_case_id_gantt_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['completed_by_id'], ['users.id'], name=op.f('fk_case_tasks_completed_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_case_tasks_group_id_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_case_tasks_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_case_tasks')),
    sa.UniqueConstraint('case_id', 'name', name='uq_case_task_name')
    )
    op.create_index('idx_case_tasks_case', 'case_tasks', ['case_id'], unique=False)
    op.create_index('idx_case_tasks_owner_status', 'case_tasks', ['owner_id', 'status'], unique=False)
    op.create_table('template_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_name', sa.String(length=128), nullable=False),
    sa.Column('cron', sa.String(length=64), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('target_date_offset_s', sa.Integer(), nullable=False),
    sa.Column('name_template', sa.String(length=256), nullable=False),
    sa.Column('params', JSONType, nullable=False),
    sa.Column('role_assignments', JSONType, nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_case_id', sa.Integer(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_template_schedules_created_by_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['last_case_id'], ['gantt_cases.id'], name=op.f('fk_template_schedules_last_case_id_gantt_cases'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_template_schedules')),
    sa.UniqueConstraint('template_name', name=op.f('uq_template_schedules_template_name'))
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('case_task_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('before_state', JSONType, nullable=True),
    sa.Column('after_state', JSONType, nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_audit_events_actor_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['case_id'], ['gantt_cases.id'], name=op.f('fk_audit_events_case_id_gantt_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_task_id'], ['case_tasks.id'], name=op.f('fk_audit_events_case_task_id_case_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('idx_audit_case', 'audit_events', ['case_id', 'created_at'], unique=False)
    op.create_table('job_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=32), nullable=False),
    sa.Column('case_task_id', sa.Integer(), nullable=True),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('payload', JSONType, nullable=False),
    sa.Column('run_after', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('locked_by', sa.String(length=128), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['gantt_cases.id'], name=op.f('fk_job_queue_case_id_gantt_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_task_id'], ['case_tasks.id'], name=op.f('fk_job_queue_case_task_id_case_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_queue'))
    )
    op.create_index('idx_job_queue_pickup', 'job_queue', ['run_after'], unique=False, postgresql_where=sa.text('locked_by IS NULL'), sqlite_where=sa.text('locked_by IS NULL'))
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('case_task_id', sa.Integer(), nullable=True),
    sa.Column('dedup_key', sa.String(length=256), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['gantt_cases.id'], name=op.f('fk_notifications_case_id_gantt_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['case_task_id'], ['case_tasks.id'], name=op.f('fk_notifications_case_task_id_case_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_notifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notif_unread', 'notifications', ['user_id', 'created_at'], unique=False, postgresql_where=sa.text('read_at IS NULL'), sqlite_where=sa.text('read_at IS NULL'))
    op.create_index('uq_notif_dedup', 'notifications', ['dedup_key'], unique=True, postgresql_where=sa.text('dedup_key IS NOT NULL'), sqlite_where=sa.text('dedup_key IS NOT NULL'))
    op.create_table('task_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('predecessor_id', sa.Integer(), nullable=False),
    sa.Column('successor_id', sa.Integer(), nullable=False),
    sa.Column('lag_seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('lag_seconds >= 0', name=op.f('ck_task_dependencies_non_negative_lag')),
    sa.CheckConstraint('predecessor_id <> successor_id', name=op.f('ck_task_dependencies_no_self_dependency')),
    sa.ForeignKeyConstraint(['case_id'], ['gantt_cases.id'], name=op.f('fk_task_dependencies_case_id_gantt_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['predecessor_id'], ['case_tasks.id'], name=op.f('fk_task_dependencies_predecessor_id_case_tasks'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['successor_id'], ['case_tasks.id'], name=op.f('fk_task_dependencies_successor_id_case_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_dependencies')),
    sa.UniqueConstraint('predecessor_id', 'successor_id', name='uq_dependency_pair')
    )
    op.create_index('idx_deps_pred', 'task_dependencies', ['predecessor_id'], unique=False)
    op.create_index('idx_deps_succ', 'task_dependencies', ['successor_id'], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_task_id', sa.Integer(), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('handler_name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('request_payload', JSONType, nullable=False),
    sa.Column('response_payload', JSONType, nullable=True),
    sa.Column('external_ref', sa.String(length=256), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['case_task_id'], ['case_tasks.id'], name=op.f('fk_task_runs_case_task_id_case_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_task_runs')),
    sa.UniqueConstraint('case_task_id', 'attempt', name='uq_run_attempt')
    )
    op.create_table('notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['notification_id'], ['notifications.id'], name=op.f('fk_notification_deliveries_notification_id_notifications'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification_deliveries')),
    sa.UniqueConstraint('notification_id', 'channel', name='uq_delivery_channel')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_deliveries')
    op.drop_table('task_runs')
    op.drop_index('idx_deps_succ', table_name='task_dependencies')
    op.drop_index('idx_deps_pred', table_name='task_dependencies')
    op.drop_table('task_dependencies')
    op.drop_index('uq_notif_dedup', table_name='notifications', postgresql_where=sa.text('dedup_key IS NOT NULL'), sqlite_where=sa.text('dedup_key IS NOT NULL'))
    op.drop_index('idx_notif_unread', table_name='notifications', postgresql_where=sa.text('read_at IS NULL'), sqlite_where=sa.text('read_at IS NULL'))
    op.drop_table('notifications')
    op.drop_index('idx_job_queue_pickup', table_name='job_queue', postgresql_where=sa.text('locked_by IS NULL'), sqlite_where=sa.text('locked_by IS NULL'))
    op.drop_table('job_queue')
    op.drop_index('idx_audit_case', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('template_schedules')
    op.drop_index('idx_case_tasks_owner_status', table_name='case_tasks')
    op.drop_index('idx_case_tasks_case', table_name='case_tasks')
    op.drop_table('case_tasks')
    op.drop_table('task_templates')
    op.drop_table('notification_preferences')
    op.drop_table('group_members')
    op.drop_index('uq_gantt_template_draft', table_name='gantt_templates', postgresql_where=sa.text("status = 'draft'"), sqlite_where=sa.text("status = 'draft'"))
    op.drop_table('gantt_templates')
    op.drop_index('idx_cases_status_target', table_name='gantt_cases')
    op.drop_index('idx_cases_health', table_name='gantt_cases', postgresql_where=sa.text("status = 'active'"), sqlite_where=sa.text("status = 'active'"))
    op.drop_table('gantt_cases')
    op.drop_table('api_credentials')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_table('calendars')
    # ### end Alembic commands ###
